-- ==========================================
-- 1. DROP EXISTING TABLES (CLEAN SLATE)
-- ==========================================
DROP TABLE IF EXISTS cash_deposits;
DROP TABLE IF EXISTS installation_payments;
DROP TABLE IF EXISTS installation_fees;
DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS meter_records;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS rate_history;
DROP TABLE IF EXISTS rates;
DROP TABLE IF EXISTS areas;

-- ==========================================
-- 2. CREATE MASTER TABLES
-- ==========================================

-- TABLE: AREAS
CREATE TABLE areas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    code TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- TABLE: RATES (Master Tarif)
CREATE TABLE rates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,         -- e.g. "Tarif Standar 2026"
    code TEXT UNIQUE,           -- e.g. "R1"
    flat_rate NUMERIC NOT NULL, -- Harga per m3
    maintenance_fee NUMERIC NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- TABLE: RATE_HISTORY (Riwayat Perubahan Tarif)
-- Agar tagihan lama tidak ikut berubah saat tarif master diedit
CREATE TABLE rate_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rate_id BIGINT NOT NULL REFERENCES rates(id) ON DELETE CASCADE,
    flat_rate NUMERIC NOT NULL,
    maintenance_fee NUMERIC NOT NULL,
    effective_from DATE NOT NULL DEFAULT CURRENT_DATE,
    effective_to DATE, -- NULL means currently active
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- TABLE: CUSTOMERS
CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    connection_number TEXT NOT NULL UNIQUE,
    address TEXT,
    phone TEXT,
    status TEXT DEFAULT 'active', -- active, inactive, disconnected
    
    area_id BIGINT REFERENCES areas(id) ON DELETE SET NULL,
    rate_id BIGINT REFERENCES rates(id) ON DELETE SET NULL,
    
    credit_balance NUMERIC DEFAULT 0, -- Saldo titipan kelebihan bayar
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- 3. BIAYA PASANG & CICILAN
-- ==========================================

-- TABLE: INSTALLATION_FEES
CREATE TABLE installation_fees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    total_amount NUMERIC NOT NULL, -- Total biaya pasang
    paid_amount NUMERIC DEFAULT 0, -- Yang sudah dibayar
    remaining_amount NUMERIC GENERATED ALWAYS AS (total_amount - paid_amount) STORED,
    status TEXT DEFAULT 'pending', -- pending, partial, paid
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- TABLE: INSTALLATION_PAYMENTS (Log Cicilan)
CREATE TABLE installation_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    installation_fee_id BIGINT NOT NULL REFERENCES installation_fees(id) ON DELETE CASCADE,
    amount NUMERIC NOT NULL,
    payment_date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    method TEXT DEFAULT 'cash', -- cash, transfer
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- 4. PENCATATAN & TAGIHAN
-- ==========================================

-- TABLE: METER_RECORDS
CREATE TABLE meter_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    
    month INT NOT NULL,
    year INT NOT NULL,
    
    meter_last INT NOT NULL DEFAULT 0,
    meter_current INT NOT NULL DEFAULT 0,
    usage INT GENERATED ALWAYS AS (meter_current - meter_last) STORED,
    
    -- SNAPSHOT TARIF SAAT PENCATATAN (PENTING!)
    rate_snapshot NUMERIC NOT NULL, -- Harga per m3 saat itu
    maintenance_snapshot NUMERIC NOT NULL, -- Abonemen saat itu
    
    -- TAGIHAN
    bill_amount NUMERIC GENERATED ALWAYS AS (
        ((meter_current - meter_last) * rate_snapshot) + maintenance_snapshot
    ) STORED,
    
    paid_amount NUMERIC DEFAULT 0, -- Berapa yang sudah dibayar untuk bulan ini
    status TEXT DEFAULT 'unpaid', -- unpaid, partial, paid
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(customer_id, month, year)
);

-- TABLE: TRANSACTIONS (Log Pembayaran Bulanan)
CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    
    total_amount NUMERIC NOT NULL, -- Total uang yang disetor user saat itu
    
    -- Detail alokasi pembayaran (karena 1x bayar bisa untuk 3 bulan)
    -- Format JSON: [{"record_id": 1, "amount": 10000}, {"record_id": 2, "amount": 5000}]
    allocation_details JSONB, 
    
    applied_credit NUMERIC DEFAULT 0, -- Saldo titipan yang dipakai
    new_credit NUMERIC DEFAULT 0, -- Sisa uang yang masuk ke saldo titipan
    
    payment_date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    method TEXT DEFAULT 'cash', -- cash, transfer
    notes TEXT,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- 5. SETORAN BENDAHARA
-- ==========================================

-- TABLE: CASH_DEPOSITS
CREATE TABLE cash_deposits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collector_name TEXT NOT NULL, -- Nama petugas
    deposit_date DATE NOT NULL DEFAULT CURRENT_DATE,
    
    total_cash NUMERIC DEFAULT 0,
    total_transfer NUMERIC DEFAULT 0,
    total_amount NUMERIC GENERATED ALWAYS AS (total_cash + total_transfer) STORED,
    
    notes TEXT,
    evidence_url TEXT, -- Bukti setor (foto)
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- 6. SEED DATA
-- ==========================================

-- Seed Areas
INSERT INTO areas (name, code) VALUES 
('Dusun I - Krajan', 'D1'), ('Dusun II - Nepen', 'D2'), ('Perumahan Griya Asri', 'PGA');

-- Seed Rates (2025 Old Rate)
INSERT INTO rates (name, code, flat_rate, maintenance_fee) VALUES 
('Tarif Lama 2025', 'OLD', 1000, 3000); 

-- Seed Rate History for Old Rate
INSERT INTO rate_history (rate_id, flat_rate, maintenance_fee, effective_from, effective_to) 
VALUES (1, 1000, 3000, '2025-01-01', '2025-12-31');

-- Update Rate to New 2026 Price
UPDATE rates SET name = 'Tarif Standar 2026', code = 'STD', flat_rate = 1300, maintenance_fee = 5000 WHERE id = 1;

-- Seed Rate History for New Rate
INSERT INTO rate_history (rate_id, flat_rate, maintenance_fee, effective_from) 
VALUES (1, 1300, 5000, '2026-01-01');

-- Seed Customers
INSERT INTO customers (name, connection_number, area_id, rate_id, status) VALUES
('Pelanggan A (Nunggak)', 'SR-001', 1, 1, 'active'),
('Pelanggan B (Lancar)', 'SR-002', 1, 1, 'active'),
('Pelanggan C (Nyicil Pasang)', 'SR-003', 2, 1, 'active');

-- Seed Installation Fee (Pelanggan C masih nyicil)
INSERT INTO installation_fees (customer_id, total_amount, paid_amount, status) VALUES
(3, 500000, 200000, 'partial');

-- Seed Meter Records (Simulasi Kasus User)
-- Pelanggan A: Nunggak 2022 (Tarif 1000) vs 2026 (Tarif 1300)
-- Kita anggap ID 1 itu Tarif yg aktif saat itu. 

-- Tagihan Lama (Pakai harga 1000)
INSERT INTO meter_records (customer_id, month, year, meter_last, meter_current, rate_snapshot, maintenance_snapshot) VALUES
(1, 12, 2025, 100, 110, 1000, 3000); -- Usage 10. Bill: (10*1000)+3000 = 13.000

-- Tagihan Baru (Pakai harga 1300)
INSERT INTO meter_records (customer_id, month, year, meter_last, meter_current, rate_snapshot, maintenance_snapshot) VALUES
(1, 1, 2026, 110, 120, 1300, 5000); -- Usage 10. Bill: (10*1300)+5000 = 18.000


-- ==========================================
-- 7. ENABLE RLS
-- ==========================================
ALTER TABLE areas ENABLE ROW LEVEL SECURITY;
ALTER TABLE rates ENABLE ROW LEVEL SECURITY;
ALTER TABLE rate_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE installation_fees ENABLE ROW LEVEL SECURITY;
ALTER TABLE installation_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE meter_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE cash_deposits ENABLE ROW LEVEL SECURITY;

-- OPEN ACCESS POLICY (Easy Dev Mode)
CREATE POLICY "Public Areas" ON areas FOR ALL USING (true);
CREATE POLICY "Public Rates" ON rates FOR ALL USING (true);
CREATE POLICY "Public Rate History" ON rate_history FOR ALL USING (true);
CREATE POLICY "Public Customers" ON customers FOR ALL USING (true);
CREATE POLICY "Public InstFees" ON installation_fees FOR ALL USING (true);
CREATE POLICY "Public InstPay" ON installation_payments FOR ALL USING (true);
CREATE POLICY "Public Meters" ON meter_records FOR ALL USING (true);
CREATE POLICY "Public Tx" ON transactions FOR ALL USING (true);
CREATE POLICY "Public Deposits" ON cash_deposits FOR ALL USING (true);
-- ==========================================
-- 8. MIGRATION FOR DEPOSIT TRACKING
-- ==========================================
-- Add tracking columns to transactions
ALTER TABLE transactions 
ADD COLUMN IF NOT EXISTS is_deposited BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS deposit_id BIGINT REFERENCES cash_deposits(id) ON DELETE SET NULL;

-- Add tracking columns to installation_payments
ALTER TABLE installation_payments 
ADD COLUMN IF NOT EXISTS is_deposited BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS deposit_id BIGINT REFERENCES cash_deposits(id) ON DELETE SET NULL;

-- Add tracking column to cash_deposits
ALTER TABLE cash_deposits
ADD COLUMN IF NOT EXISTS transaction_count INT DEFAULT 0;
